dist: trusty

language: scala

scala:
  - 2.11.12
  - 2.12.10

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalastyle
  - sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
